# Site settings
name: WANG T.F. BLOG
email: 493710524@qq.com
author: WANG T.F.
url: https://github.com/wang-tf/
resume_site: https://github.com/wang-tf/
github: https://github.com/wang-tf/
baseurl: ""
description: Actually, less is more!
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wang-tf
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
